### ISSUE TITLE
Error on 'not ok'

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#21]
**Describe the bug**
On test failures, [bats](https://github.com/sstephenson/bats) produces tap output that `tap-junit` cannot parse; it results in a “missing attribute value” error.

**To Reproduce**
1. Create a file `tap.txt` with these contents:
```
1..3
ok 1 simple comparison - successful
not ok 2 simple comparison - unsuccessful
ok 3 # skip simple comparison - ignored
```
2. Ensure `tap-junit` is installed:
```
npm i -D tap-junit
```
3. Get the `tap-junit` version:
```
~/node_modules/tap-junit/bin/tap-junit --version
```
4. Pipe the `tap.txt` file into `tap-junit`:
```
cat tap3.txt | ~/node_modules/tap-junit/bin/tap-junit
```

**Expected behavior**
1. On step 2, the installation is successful.
2. On step 3, the version is properly displayed.
3. On step 4, the conversion to XML is successful.

**Actual behavior**
1. OK: On step 2, the installation is successful.
2. OK: On step 3, the version is properly displayed:
```
$ ~/node_modules/tap-junit/bin/tap-junit --version
3.0.1
```
3. NOK: On step 4, the conversion to XML is not successful:
```
cat tap.txt | ~/node_modules/tap-junit/bin/tap-junit 
/Users/ernst/node_modules/xmlbuilder/lib/XMLAttribute.js:14
        throw new Error("Missing attribute value. " + this.debugInfo(name));
        ^

Error: Missing attribute value. attribute: {type}, parent: <failure>
    at new XMLAttribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLAttribute.js:14:15)
    at XMLElement.module.exports.XMLElement.attribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:72:35)
    at XMLElement.module.exports.XMLElement.attribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:65:16)
    at new XMLElement (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:24:14)
    at XMLElement.module.exports.XMLNode.node (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:163:15)
    at XMLElement.module.exports.XMLNode.element (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:110:28)
    at XMLElement.module.exports.XMLNode.ele (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:392:19)
    at suite.asserts.forEach.test (/Users/ernst/node_modules/tap-junit/src/serialize.js:28:20)
    at Array.forEach (<anonymous>)
    at testCases.forEach.suite (/Users/ernst/node_modules/tap-junit/src/serialize.js:20:19)
```

**Additional information:**
- OS: macOS 10.14.2
```
Darwin Ernsts-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by znerd** [comment]
The problem appears to be in `serialize.js`, in this statement:
```
testCaseEl.ele('failure', {
          type: test.error.operator,
          message: test.raw
        }, `
    ---
${test.error.raw}
${test.error.stack}
    ---
        `)
```

Apparently `test.error.operator` is `null` here.

However, I cannot find any code in `tap-junit` that sets `test.error.operator`, so this logic might be in a dependency. It seems `tap-out` is the most logical candidate here (mentioned in `package.json`).

**Comment by znerd** [comment]
Using `tap-out` 3.0 on that same file, I'm getting this:
```
$ cat tap.txt | ~/node_modules/tap-out/bin/cmd.js
{
  "tests": [],
  "asserts": [
    {
      "type": "assert",
      "raw": "ok 1 simple comparison - successful",
      "ok": true,
      "number": 1,
      "name": "simple comparison - successful",
      "test": 0
    },
    {
      "type": "assert",
      "raw": "not ok 2 simple comparison - unsuccessful",
      "ok": false,
      "number": 2,
      "name": "simple comparison - unsuccessful",
      "error": {},
      "test": 0
    },
    {
      "type": "assert",
      "raw": "ok 3 # skip simple comparison - ignored",
      "ok": true,
      "number": 3,
      "name": "# skip simple comparison - ignored",
      "test": 0
    }
  ],
  "versions": [],
  "results": [],
  "comments": [],
  "plans": [
    {
      "type": "plan",
      "raw": "1..3",
      "from": 1,
      "to": 3
    }
  ],
  "pass": [
    {
      "type": "assert",
      "raw": "ok 1 simple comparison - successful",
      "ok": true,
      "number": 1,
      "name": "simple comparison - successful",
      "test": 0
    },
    {
      "type": "assert",
      "raw": "ok 3 # skip simple comparison - ignored",
      "ok": true,
      "number": 3,
      "name": "# skip simple comparison - ignored",
      "test": 0
    }
  ],
  "fail": [
    {
      "type": "assert",
      "raw": "not ok 2 simple comparison - unsuccessful",
      "ok": false,
      "number": 2,
      "name": "simple comparison - unsuccessful",
      "error": {},
      "test": 0
    }
  ],
  "errors": []
}
```

Note that `"fail" -> "error"` is an empty array: `{}`.

**Comment by znerd** [comment]
The problem even occurs when using the first sample on the TAP website [testanything.org](https://testanything.org/):
```
$ cat tapX.txt 
1..4
ok 1 - Input file opened
not ok 2 - First line of the input valid
ok 3 - Read the rest of the file
not ok 4 - Summarized correctly # TODO Not written yet
$ cat tapX.txt | ~/node_modules/tap-junit/bin/tap-junit
/Users/ernst/node_modules/xmlbuilder/lib/XMLAttribute.js:14
        throw new Error("Missing attribute value. " + this.debugInfo(name));
        ^

Error: Missing attribute value. attribute: {type}, parent: <failure>
    at new XMLAttribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLAttribute.js:14:15)
    at XMLElement.module.exports.XMLElement.attribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:72:35)
    at XMLElement.module.exports.XMLElement.attribute (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:65:16)
    at new XMLElement (/Users/ernst/node_modules/xmlbuilder/lib/XMLElement.js:24:14)
    at XMLElement.module.exports.XMLNode.node (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:163:15)
    at XMLElement.module.exports.XMLNode.element (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:110:28)
    at XMLElement.module.exports.XMLNode.ele (/Users/ernst/node_modules/xmlbuilder/lib/XMLNode.js:392:19)
    at suite.asserts.forEach.test (/Users/ernst/node_modules/tap-junit/src/serialize.js:28:20)
    at Array.forEach (<anonymous>)
    at testCases.forEach.suite (/Users/ernst/node_modules/tap-junit/src/serialize.js:20:19)
```

**Comment by dhershman1** [comment]
Alright, I will take a look into this I added two new test cases involving your provided examples.

Edit (02/15/2019): Upon first investigation it appears that the out from tape creates a full stack for a failure. Which looks something like this:

```
# 2 === 1
not ok 2 should be equal
  ---
    operator: equal
    expected: 1
    actual:   2
    at: Test.t (/Users/dhershman/Documents/projects/personal/modules/tap-junit/tests/fail.js:13:5)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:76:32)
          at Test.equal (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:384:10)
          at Test.bound [as equal] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:76:32)
          at Test.t (/Users/dhershman/Documents/projects/personal/modules/tap-junit/tests/fail.js:13:5)
          at Test.bound [as _cb] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:76:32)
          at Test.run (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:95:10)
          at Test.bound [as run] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/test.js:76:32)
          at Immediate.next [as _onImmediate] (/Users/dhershman/Documents/projects/personal/modules/tap-junit/node_modules/tape/lib/results.js:71:15)
          at runCallback (timers.js:705:18)
  ...
```

This is where tap-out get's that extra information. Like you said without it those fields are undefined. So I can probably set a default or try to figure out operator logic myself. Not sure which would be better at the moment.

**Comment by dhershman1** [comment]
I believe I have a patch ready in PR #22 to address this issue. May try to find some other similar examples to throw at the serializer first

**Comment by dhershman1** [comment]
And the patch should be merged in and published now.
